import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const distDir = "dist";

function copyStaticAssets() {
	try {
		fs.mkdirSync(distDir, { recursive: true });
		fs.copyFileSync(path.resolve("styles.css"), path.join(distDir, "styles.css"));
		fs.copyFileSync(path.resolve("manifest.json"), path.join(distDir, "manifest.json"));
		console.log("Copied styles.css and manifest.json to", distDir);
	} catch (err) {
		console.error("Failed to copy static assets:", err);
	}
}

esbuild
	.build({
		banner: {
			js: banner,
		},
		minify: prod ? true : false,
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/closebrackets",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/comment",
			"@codemirror/fold",
			"@codemirror/gutter",
			"@codemirror/highlight",
			"@codemirror/history",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/matchbrackets",
			"@codemirror/panel",
			"@codemirror/rangeset",
			"@codemirror/rectangular-selection",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/stream-parser",
			"@codemirror/text",
			"@codemirror/tooltip",
			"@codemirror/view",
			...builtins,
		],
		format: "cjs",
		watch: !prod
			? {
				onRebuild(error) {
					if (error) console.error("Watch build failed:", error);
					else copyStaticAssets();
				},
			}
			: false,
		target: "es2016",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: path.join(distDir, "main.js"),
	})
	.then(() => {
		copyStaticAssets();
	})
	.catch(() => process.exit(1));
